[server]
headless = true
runOnSave = false
maxUploadSize = 10

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#2196F3"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#31333F"
font = "monospace"
